apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: movie-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-nginx
  template:
    metadata:
      labels:
        app: movie-nginx
    spec:
      containers:
      - name: nginx
        image: plutocholia/movie-nginx:v1.2
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: regcred