---

- hosts: db_servers
  become: true
  vars_files:
    - vars/mysql_defaults.yml
    - vars/redis_defaults.yml
  
  pre_tasks:
    - name: installing updates (Ubuntu)
      tags: always, clean
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

  tasks:
    - name: Installing mysql via apt
      tags: clean
      apt:
        name: 
          - mysql-server
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu" 