---

- hosts: db_servers
  become: true
  vars_files:
    - vars/mysql_defaults.yml
  
  pre_tasks:
    - name: installing updates (Ubuntu)
      tags: always, clean
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

  tasks:
    - name: Installing mysql via apt
      tags: clean
      apt:
        name: 
          - mysql-server
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu" 
    
    - name: installing pymysql
      tags: clean
      pip:
        name: pymysql
        state: present

    - name:
      service:
        name: mysql
        state: started
        enabled: yes

    - name: root password for all accounts
      tags: clean
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Ensure Anonymous user(s) are not in the database
      tags: clean
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: '' 
        host: "{{ item }}"
        state: absent
      with_items:
        - localhost
        - "{{ ansible_hostname }}"
    
    - name: template mysqld.cnf.j2 to remote host
      tags: clean, conf
      template:
        src: templates/mysqld.cnf.j2
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root
        mode: 0644
      notify: restarting mysql
    
  handlers:
    - name: restarting mysql
      tags: clean, conf
      service: 
        name: mysql
        state: restarted 
        enabled: yes